import { NextResponse, type NextRequest } from "next/server";
import { handleRouteError } from "@/app/api/_lib/handleRouteError";
import { readJsonObject } from "@/app/api/_lib/readJsonBody";
import { requireUser } from "@/app/api/_lib/requireUser";
import { generateOutreachMessage, saveOutreachDraft } from "@/application/use-cases/employability/EmploymentAiActions";
import { assertEmploymentUser } from "@/application/use-cases/employability/profileHelpers";
import { SupabaseAuthRepository } from "@/infrastructure/supabase/auth/SupabaseAuthRepository";
import { SupabaseApplicationRepository } from "@/infrastructure/supabase/repositories/SupabaseEmploymentWorkflowRepositories";
export async function GET(request: NextRequest, { params }: { params: Promise<{ id: string }> }) { try { const { user, accessToken } = await requireUser(request, new SupabaseAuthRepository()); assertEmploymentUser(user); const research = await new SupabaseApplicationRepository().getResearch((await params).id, accessToken); return NextResponse.json(research); } catch (error) { return handleRouteError(error); } }
export async function POST(request: NextRequest, { params }: { params: Promise<{ id: string }> }) { try { const { user, accessToken } = await requireUser(request, new SupabaseAuthRepository()); const body = await readJsonObject(request); return NextResponse.json(await generateOutreachMessage({ applications: new SupabaseApplicationRepository() }, { requestedBy: user, accessToken, applicationId: (await params).id, research: { recruiterName: String(body.recruiterName || ""), recruiterRole: String(body.recruiterRole || ""), companyTenureNote: String(body.companyTenureNote || ""), recentCompanyFact: String(body.recentCompanyFact || ""), commonGroundNote: String(body.commonGroundNote || "") } })); } catch (error) { return handleRouteError(error); } }
export async function PUT(request: NextRequest, { params }: { params: Promise<{ id: string }> }) { try { const { user, accessToken } = await requireUser(request, new SupabaseAuthRepository()); const body = await readJsonObject(request); return NextResponse.json(await saveOutreachDraft({ applications: new SupabaseApplicationRepository() }, { requestedBy: user, accessToken, applicationId: (await params).id, research: { jobApplicationId: (await params).id, recruiterName: String(body.recruiterName || ""), recruiterRole: String(body.recruiterRole || ""), companyTenureNote: String(body.companyTenureNote || ""), recentCompanyFact: String(body.recentCompanyFact || ""), commonGroundNote: String(body.commonGroundNote || ""), outreachMessage: String(body.outreachMessage || ""), completedAt: null } })); } catch (error) { return handleRouteError(error); } }
