import { jsonInput } from "./common";

export const extractJobKeywordsPrompt = (jobText: string) => `Extrae entre 5 y 18 palabras o frases clave presentes de forma explícita en la vacante. No agregues sinónimos ni conocimientos externos. Responde {"keywords":[{"keyword":"...","relevance":"high|medium|low"}],"companyName":null|"...","roleTitle":null|"..."}.\nVACANTE:\n${jobText}`;
export const jobFitMatrixPrompt = (input: unknown) => `Compara los requisitos explícitos de la vacante con las fuentes del perfil entregadas. Por cada requisito importante responde una matriz honesta. Solo puedes usar evidenceRefs que existan en SOURCES. Si no existe soporte, usa status "not_demonstrated" y evidenceRefs []. No sugieras agregar experiencia como si fuera cierta. La sugerencia debe describir una acción honesta para el usuario, no decidir si debe postularse. Responde {"items":[{"requirement":"...","priority":"indispensable|important|desirable","status":"demonstrated|partial|not_demonstrated","evidenceRefs":["id"],"suggestion":"..."}]}.\nDATOS:\n${jsonInput(input)}`;
export const evidenceQuestionPrompt = (claim: string) => `Formula una o dos preguntas concretas para confirmar una cantidad, frecuencia o resultado del logro. No redactes un bullet. Responde {"questions":["..."]}.\nLOGRO: ${claim}`;
export const draftCvBulletPrompt = (input: unknown) => `Propón exactamente tres alternativas distintas de un bullet de CV, cada una de máximo 32 palabras. Usa verbo de acción, contexto y únicamente un resultado comprobable. Evita clichés como "responsable de". Si evidence.metricConfirmedByUser no es true, no incluyas ninguna cifra, porcentaje, moneda, rango ni cantidad escrita con palabras. Usa solo datos suministrados. Responde {"alternatives":["...","...","..."],"qualitativeOnly":true|false}.\nDATOS:\n${jsonInput(input)}`;
export const draftCvSummaryPrompt = (input: unknown) => `Redacta un headline de máximo 12 palabras y un resumen de 45 a 70 palabras para un CV. Usa únicamente perfil y keywords entregados; no inventes experiencia ni habilidades. Responde {"headline":"...","summary":"..."}.\nDATOS:\n${jsonInput(input)}`;
export const draftCvSummaryOptionsPrompt = (input: unknown) => `Propón exactamente tres alternativas distintas de headline (máximo 12 palabras) y resumen profesional (45 a 70 palabras) para el CV. Usa únicamente perfil, experiencias seleccionadas y keywords entregados; no inventes experiencia ni habilidades y evita promesas o tono inflado. Responde {"alternatives":[{"headline":"...","summary":"..."},{"headline":"...","summary":"..."},{"headline":"...","summary":"..."}]}.\nDATOS:\n${jsonInput(input)}`;
export const cvCoherenceCheckPrompt = (input: unknown) => `Actúa como auditor adversarial del CV. Identifica solamente vaguedad, redundancia, keyword stuffing, tono inflado y afirmaciones sin soporte visible. No modifiques el CV, no apruebes cifras, no revises ortografía ni extensión. Da hasta cinco observaciones accionables, breves y respetuosas. Responde {"notes":["..."]}.\nCV:\n${jsonInput(input)}`;
export const outreachMessagePrompt = (input: unknown) => `Redacta un mensaje INICIAL de LinkedIn de 60 a 100 palabras. El usuario inicia el contacto: la persona destinataria todavía NO ha enviado ningún mensaje. Abre con un saludo directo, por ejemplo "Hola, [nombre]", y escribe en primera persona como el candidato.

Prohibido asumir, insinuar o agradecer un contacto previo. No uses expresiones como "gracias por tu mensaje", "me da gusto saber", "como me comentaste", "retomando nuestra conversación", "responderte" o cualquier formulación propia de una respuesta o seguimiento.

Usa exclusivamente los DATOS entregados. Solo menciona empresa, puesto, etapa, trayectoria del reclutador, dato reciente o punto en común si está explícitamente escrito allí; no deduzcas que alguien es fundador, autodidacta, experto, está contratando o tiene una conversación previa. Si falta un dato, omítelo. No prometas resultados ni inventes experiencia, habilidades, motivaciones o logros del candidato. Cierra con una invitación breve y respetuosa a conversar sobre la oportunidad.

Responde {"message":"..."}.\nDATOS:\n${jsonInput(input)}`;
export const ikigaiSynthesisPrompt = (input: unknown) => `Propón una síntesis de ikigai de 45 a 70 palabras, usando únicamente las cuatro respuestas. Debe presentarse como sugerencia, no diagnóstico ni consejo definitivo. Responde {"synthesis":"..."}.\nDATOS:\n${jsonInput(input)}`;
