import { UseCaseError } from "@/application/errors";
import type { AchievementEvidence, CvContent, CvQualityCheckResult, CvStatus, CvVersion, JobApplication, JobApplicationStatusEvent, JobKeyword, JobTarget, RecruiterResearch } from "@/domain/entities";
import type { ApplicationRepository, CvRepository, EvidenceRepository, JobTargetRepository } from "@/domain/repositories";
import { createServerSupabaseClient } from "@/infrastructure/supabase/client";

type Row = Record<string, unknown>;
const asText = (v: unknown) => typeof v === "string" ? v : "";
const nullableText = (v: unknown) => typeof v === "string" ? v : null;
function target(row: Row, keywords: JobKeyword[] = []): JobTarget { return { id: asText(row.id), userId: asText(row.user_id), sourceSite: row.source_site as JobTarget["sourceSite"], rawText: asText(row.raw_text), companyName: nullableText(row.company_name), roleTitle: nullableText(row.role_title), createdAt: asText(row.created_at), keywords }; }
function keyword(row: Row): JobKeyword { return { id: asText(row.id), jobTargetId: asText(row.job_target_id), keyword: asText(row.keyword), relevance: row.relevance as JobKeyword["relevance"], matchedInProfile: row.matched_in_profile === true }; }
function evidence(row: Row): AchievementEvidence { return { id: asText(row.id), experienceEntryId: asText(row.experience_entry_id), claim: asText(row.claim), metricValue: nullableText(row.metric_value), metricConfirmedByUser: row.metric_confirmed_by_user === true, createdAt: asText(row.created_at) }; }
function cv(row: Row): CvVersion { return { id: asText(row.id), userId: asText(row.user_id), jobTargetId: asText(row.job_target_id), title: asText(row.title), status: row.status as CvStatus, content: row.content as CvContent, qualityCheck: row.quality_check as CvQualityCheckResult | null, createdAt: asText(row.created_at), updatedAt: asText(row.updated_at) }; }
function application(row: Row): JobApplication { return { id: asText(row.id), userId: asText(row.user_id), jobTargetId: asText(row.job_target_id), cvVersionId: asText(row.cv_version_id), source: row.source as JobApplication["source"], applicationType: row.application_type as JobApplication["applicationType"], companyName: asText(row.company_name), roleTitle: asText(row.role_title), status: row.status as JobApplication["status"], appliedAt: asText(row.applied_at), statusUpdatedAt: asText(row.status_updated_at) }; }
function statusEvent(row: Row): JobApplicationStatusEvent { return { id: asText(row.id), jobApplicationId: asText(row.job_application_id), status: row.status as JobApplicationStatusEvent["status"], occurredAt: asText(row.occurred_at) }; }
function research(row: Row): RecruiterResearch { return { jobApplicationId: asText(row.job_application_id), recruiterName: asText(row.recruiter_name), recruiterRole: asText(row.recruiter_role), companyTenureNote: asText(row.company_tenure_note), recentCompanyFact: asText(row.recent_company_fact), commonGroundNote: asText(row.common_ground_note), outreachMessage: asText(row.outreach_message), completedAt: nullableText(row.completed_at) }; }
function failure(error: { message: string } | null, fallback: string): never { throw new UseCaseError(error?.message || fallback, 500); }

export class SupabaseJobTargetRepository implements JobTargetRepository {
  async listJobTargets(accessToken: string): Promise<JobTarget[]> { const c = createServerSupabaseClient(accessToken); const { data, error } = await c.from("job_targets").select("*, job_keywords(*)").order("created_at", { ascending: false }); if (error) return failure(error, "No se pudieron cargar vacantes."); return ((data || []) as Row[]).map((r) => target(r, ((r.job_keywords as Row[] | null) || []).map(keyword))); }
  async getJobTarget(id: string, accessToken: string): Promise<JobTarget | null> { const c = createServerSupabaseClient(accessToken); const { data, error } = await c.from("job_targets").select("*, job_keywords(*)").eq("id", id).maybeSingle(); if (error) return failure(error, "No se pudo cargar la vacante."); return data ? target(data as Row, (((data as Row).job_keywords as Row[] | null) || []).map(keyword)) : null; }
  async createJobTarget(input: { sourceSite: JobTarget["sourceSite"]; rawText: string; companyName: string | null; roleTitle: string | null }, accessToken: string): Promise<JobTarget> { const c = createServerSupabaseClient(accessToken); const { data: auth } = await c.auth.getUser(); if (!auth.user) throw new UseCaseError("No se pudo identificar al usuario.", 401); const { data, error } = await c.from("job_targets").insert({ user_id: auth.user.id, source_site: input.sourceSite, raw_text: input.rawText, company_name: input.companyName, role_title: input.roleTitle }).select("*").single(); if (error || !data) return failure(error, "No se pudo guardar la vacante."); return target(data as Row); }
  async saveKeywords(jobTargetId: string, items: Array<Omit<JobKeyword, "id" | "jobTargetId">>, accessToken: string): Promise<JobKeyword[]> { const c = createServerSupabaseClient(accessToken); const { error: deleted } = await c.from("job_keywords").delete().eq("job_target_id", jobTargetId); if (deleted) return failure(deleted, "No se pudieron reemplazar keywords."); const { data, error } = await c.from("job_keywords").insert(items.map((i) => ({ job_target_id: jobTargetId, keyword: i.keyword, relevance: i.relevance, matched_in_profile: i.matchedInProfile }))).select("*"); if (error) return failure(error, "No se pudieron guardar keywords."); return ((data || []) as Row[]).map(keyword); }
}

export class SupabaseEvidenceRepository implements EvidenceRepository {
  async listByExperience(experienceEntryId: string, accessToken: string): Promise<AchievementEvidence[]> { const { data, error } = await createServerSupabaseClient(accessToken).from("achievement_evidence").select("*").eq("experience_entry_id", experienceEntryId).order("created_at"); if (error) return failure(error, "No se pudo cargar evidencia."); return ((data || []) as Row[]).map(evidence); }
  async create(input: Omit<AchievementEvidence, "id" | "createdAt">, accessToken: string): Promise<AchievementEvidence> { const { data, error } = await createServerSupabaseClient(accessToken).from("achievement_evidence").insert({ experience_entry_id: input.experienceEntryId, claim: input.claim, metric_value: input.metricValue, metric_confirmed_by_user: input.metricConfirmedByUser }).select("*").single(); if (error || !data) return failure(error, "No se pudo guardar evidencia."); return evidence(data as Row); }
}

export class SupabaseCvRepository implements CvRepository {
  async list(accessToken: string): Promise<CvVersion[]> { const { data, error } = await createServerSupabaseClient(accessToken).from("cv_versions").select("*").order("updated_at", { ascending: false }); if (error) return failure(error, "No se pudieron cargar CVs."); return ((data || []) as Row[]).map(cv); }
  async get(id: string, accessToken: string): Promise<CvVersion | null> { const { data, error } = await createServerSupabaseClient(accessToken).from("cv_versions").select("*").eq("id", id).maybeSingle(); if (error) return failure(error, "No se pudo cargar el CV."); return data ? cv(data as Row) : null; }
  async create(input: { jobTargetId: string; title: string; content: CvContent }, accessToken: string): Promise<CvVersion> { const c = createServerSupabaseClient(accessToken); const { data: auth } = await c.auth.getUser(); if (!auth.user) throw new UseCaseError("No se pudo identificar al usuario.", 401); const { data, error } = await c.from("cv_versions").insert({ user_id: auth.user.id, job_target_id: input.jobTargetId, title: input.title, content: input.content }).select("*").single(); if (error || !data) return failure(error, "No se pudo crear el CV."); return cv(data as Row); }
  async updateContent(id: string, content: CvContent, accessToken: string): Promise<CvVersion> { return this.update(id, { content, quality_check: null, status: "draft", updated_at: new Date().toISOString() }, accessToken); }
  async updateTitle(id: string, title: string, accessToken: string): Promise<CvVersion> { return this.update(id, { title, quality_check: null, status: "draft", updated_at: new Date().toISOString() }, accessToken); }
  async renameCv(id: string, title: string, accessToken: string): Promise<CvVersion> { return this.update(id, { title, updated_at: new Date().toISOString() }, accessToken); }
  async setQualityCheck(id: string, result: CvQualityCheckResult, accessToken: string): Promise<CvVersion> { return this.update(id, { quality_check: result, status: "quality_review", updated_at: new Date().toISOString() }, accessToken); }
  async setStatus(id: string, status: CvStatus, accessToken: string): Promise<CvVersion> { return this.update(id, { status, updated_at: new Date().toISOString() }, accessToken); }
  private async update(id: string, patch: Row, token: string): Promise<CvVersion> { const { data, error } = await createServerSupabaseClient(token).from("cv_versions").update(patch).eq("id", id).select("*").single(); if (error || !data) return failure(error, "No se pudo actualizar el CV."); return cv(data as Row); }
}

export class SupabaseApplicationRepository implements ApplicationRepository {
  async list(accessToken: string): Promise<JobApplication[]> { const { data, error } = await createServerSupabaseClient(accessToken).from("job_applications").select("*").order("status_updated_at", { ascending: false }); if (error) return failure(error, "No se pudieron cargar postulaciones."); return ((data || []) as Row[]).map(application); }
  async get(id: string, accessToken: string): Promise<JobApplication | null> { const { data, error } = await createServerSupabaseClient(accessToken).from("job_applications").select("*").eq("id", id).maybeSingle(); if (error) return failure(error, "No se pudo cargar la postulación."); return data ? application(data as Row) : null; }
  async create(input: Omit<JobApplication, "id" | "userId" | "statusUpdatedAt">, token: string): Promise<JobApplication> { const c = createServerSupabaseClient(token); const { data: auth } = await c.auth.getUser(); if (!auth.user) throw new UseCaseError("No se pudo identificar al usuario.", 401); const { data, error } = await c.from("job_applications").insert({ user_id: auth.user.id, job_target_id: input.jobTargetId, cv_version_id: input.cvVersionId, source: input.source, application_type: input.applicationType, company_name: input.companyName, role_title: input.roleTitle, status: input.status, applied_at: input.appliedAt }).select("*").single(); if (error || !data) return failure(error, "No se pudo registrar la postulación."); return application(data as Row); }
  async updateStatus(id: string, status: JobApplication["status"], token: string): Promise<JobApplication> { const { data, error } = await createServerSupabaseClient(token).from("job_applications").update({ status }).eq("id", id).select("*").single(); if (error || !data) return failure(error, "No se pudo actualizar la postulación."); return application(data as Row); }
  async updateType(id: string, type: JobApplication["applicationType"], token: string): Promise<JobApplication> { const { data, error } = await createServerSupabaseClient(token).from("job_applications").update({ application_type: type }).eq("id", id).select("*").single(); if (error || !data) return failure(error, "No se pudo actualizar el tipo de postulación."); return application(data as Row); }
  async listStatusEvents(token: string): Promise<JobApplicationStatusEvent[]> { const { data, error } = await createServerSupabaseClient(token).from("job_application_status_events").select("*").order("occurred_at", { ascending: false }); if (error) return failure(error, "No se pudo cargar el historial de postulaciones."); return ((data || []) as Row[]).map(statusEvent); }
  async getResearch(id: string, token: string): Promise<RecruiterResearch | null> { const { data, error } = await createServerSupabaseClient(token).from("recruiter_research").select("*").eq("job_application_id", id).maybeSingle(); if (error) return failure(error, "No se pudo cargar la investigación."); return data ? research(data as Row) : null; }
  async upsertResearch(input: RecruiterResearch, token: string): Promise<RecruiterResearch> { const { data, error } = await createServerSupabaseClient(token).from("recruiter_research").upsert({ job_application_id: input.jobApplicationId, recruiter_name: input.recruiterName, recruiter_role: input.recruiterRole, company_tenure_note: input.companyTenureNote, recent_company_fact: input.recentCompanyFact, common_ground_note: input.commonGroundNote, outreach_message: input.outreachMessage, completed_at: input.completedAt }).select("*").single(); if (error || !data) return failure(error, "No se pudo guardar la investigación."); return research(data as Row); }
}
