"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import styled from "styled-components";
import { Button } from "@/presentation/atoms/Button";
import { Input } from "@/presentation/atoms/Input";
import { Badge } from "@/presentation/atoms/Badge";
import { Modal } from "@/presentation/atoms/Modal";
import { EmptyState, LoadingState } from "@/presentation/molecules/AsyncState";
import { FormField } from "@/presentation/molecules/FormField";
import { FormStatusMessage } from "@/presentation/molecules/FormStatusMessage";
import type { EvaluationAssignment } from "@/domain/entities";
import * as evaluationService from "@/presentation/services/evaluationService";
import * as cohortService from "@/presentation/services/cohortService";
import { Select } from "@/presentation/atoms/Select";

const Page = styled.section`display:flex;flex-direction:column;gap:${p=>p.theme.spacing.xl};max-width:1040px;`; const Header = styled.div`display:flex;flex-direction:column;gap:${p=>p.theme.spacing.sm};`; const Title=styled.h1`font-size:${p=>p.theme.typography.fontSize.xl};`; const Meta=styled.p`color:${p=>p.theme.colors.textSecondary};`; const Card=styled.div`border:1px solid ${p=>p.theme.colors.border};border-radius:16px;background:${p=>p.theme.colors.surface};overflow:hidden;`; const Row=styled.article`display:grid;grid-template-columns:1fr auto;gap:${p=>p.theme.spacing.md};align-items:center;padding:${p=>p.theme.spacing.lg};border-top:1px solid ${p=>p.theme.colors.border};@media(max-width:640px){grid-template-columns:1fr;}`; const ModalForm=styled.form`display:flex;flex-direction:column;gap:${p=>p.theme.spacing.lg};`; const Actions=styled.div`display:flex;gap:${p=>p.theme.spacing.sm};justify-content:flex-end;flex-wrap:wrap;`;
function formatDate(value:string){return new Intl.DateTimeFormat("es-MX",{dateStyle:"medium",timeZone:"UTC"}).format(new Date(`${value}T00:00:00Z`));}

export default function EvaluationDetailPage({ params }: { params: Promise<{ evaluationId: string }> }) {
  const [id,setId]=useState("");const [detail,setDetail]=useState<Awaited<ReturnType<typeof evaluationService.getEvaluation>>|null>(null);const [error,setError]=useState<string|null>(null);const [selected,setSelected]=useState<EvaluationAssignment|null>(null);const [score,setScore]=useState("");const [file,setFile]=useState<File|null>(null);const [saving,setSaving]=useState(false);const [eligible,setEligible]=useState<Array<{id:string;fullName:string}>>([]);const [participantId,setParticipantId]=useState("");
  const load=async(evaluationId:string)=>{try{const next=await evaluationService.getEvaluation(evaluationId);setDetail(next);const cohort=await cohortService.getCohortDetail(next.evaluation.cohortId);setEligible(cohort.participants.filter(person=>person.isActive&&(person.role==="usuario"||person.role==="test")&&!next.assignments.some(assignment=>assignment.participantId===person.id)).map(person=>({id:person.id,fullName:person.fullName})));}catch{setError("No se pudo cargar la evaluación.");}};
  useEffect(()=>{params.then(({evaluationId})=>{setId(evaluationId);load(evaluationId);});},[params]);
  function open(assignment:EvaluationAssignment){setSelected(assignment);setScore(String(assignment.draft?.score ?? assignment.result?.score ?? ""));setFile(null);setError(null);}
  async function save(publish:boolean){if(!selected)return;const numeric=score === "" ? null : Number(score);if(numeric===null||!Number.isInteger(numeric)||numeric<0||numeric>100){setError("Ingresa una calificación entera de 0 a 100.");return;}if(publish&&!file&&!selected.draft?.fileName){setError("Selecciona el PDF antes de publicar.");return;}setSaving(true);try{let uploaded:null|{objectKey:string;fileName:string}=null;if(file)uploaded=await evaluationService.uploadPdf(id,selected.id,file);await evaluationService.saveResult(id,selected.id,{score:numeric,objectKey:uploaded?.objectKey??null,fileName:uploaded?.fileName??null,publish});setSelected(null);await load(id);}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo guardar la evaluación.");}finally{setSaving(false);}}
  async function download(assignment:EvaluationAssignment){try{await evaluationService.openEvaluationPdf(id,assignment.id);}catch{setError("No se pudo preparar la descarga.");}}
  async function addParticipant(){if(!participantId)return;try{await evaluationService.addParticipant(id,participantId);setParticipantId("");await load(id);}catch{setError("No se pudo agregar a la persona.");}}
  if(!detail)return <Page><LoadingState label="Cargando evaluación…" /></Page>; const {evaluation,assignments}=detail;
  return <Page><Button as={Link} href="/admin/evaluations" variant="ghost">← Evaluaciones</Button><Header><Title>{evaluation.title}</Title><Meta>{evaluation.cohortName} · {formatDate(evaluation.periodStart)} al {formatDate(evaluation.periodEnd)}</Meta>{evaluation.description&&<Meta>{evaluation.description}</Meta>}</Header>{error&&<FormStatusMessage variant="error">{error}</FormStatusMessage>}{evaluation.status==="active"&&eligible.length>0&&<Card><h2>Agregar participante</h2><Meta>Las personas que se integraron después se agregan de forma explícita.</Meta><Actions><Select value={participantId} onChange={event=>setParticipantId(event.target.value)}><option value="">Selecciona una persona…</option>{eligible.map(person=><option key={person.id} value={person.id}>{person.fullName}</option>)}</Select><Button onClick={addParticipant} disabled={!participantId}>Agregar</Button></Actions></Card>}<Card>{assignments.length===0?<EmptyState title="No hay participantes asignados" description="La cohorte no tenía participantes activos al crear la evaluación."/>:assignments.map(assignment=><Row key={assignment.id}><div><strong>{assignment.participantName}</strong><Meta>{assignment.participantEmail}</Meta>{assignment.result?<Meta>Calificación publicada: <strong>{assignment.result.score}/100</strong></Meta>:assignment.draft?<Meta>Borrador en progreso</Meta>:<Meta>Pendiente de evaluación</Meta>}</div><Actions>{assignment.result&&<Button variant="ghost" onClick={()=>download(assignment)}>Ver PDF</Button>}<Button variant={assignment.result?"secondary":"primary"} onClick={()=>open(assignment)}>{assignment.result?"Corregir":"Hacer evaluación"}</Button></Actions></Row>)}</Card>
    <Modal open={Boolean(selected)} onClose={()=>!saving&&setSelected(null)} ariaLabel="Hacer evaluación"><ModalForm onSubmit={event=>{event.preventDefault();void save(true);}}><h2>{selected?.participantName}</h2>{selected?.result&&<Badge tone="success">Publicada: {selected.result.score}/100</Badge>}<FormField label="Calificación (0 a 100)" htmlFor="evaluation-score"><Input id="evaluation-score" type="number" min="0" max="100" step="1" value={score} onChange={e=>setScore(e.target.value)} /></FormField><FormField label="PDF con el detalle de la evaluación" htmlFor="evaluation-file"><Input id="evaluation-file" type="file" accept="application/pdf" onChange={e=>setFile(e.target.files?.[0]??null)} />{selected?.draft?.fileName&&<Meta>Borrador actual: {selected.draft.fileName}</Meta>}<Meta>PDF, máximo 20 MB.</Meta></FormField><Actions><Button type="button" variant="ghost" onClick={()=>void save(false)} disabled={saving}>{saving?"Guardando…":"Guardar borrador"}</Button><Button type="submit" disabled={saving}>{saving?"Publicando…":"Publicar evaluación"}</Button></Actions></ModalForm></Modal>
  </Page>;
}
