"use client";
import { useEffect, useState } from "react";
import styled from "styled-components";
import { Button } from "@/presentation/atoms/Button";
import { Badge } from "@/presentation/atoms/Badge";
import { FormStatusMessage } from "@/presentation/molecules/FormStatusMessage";
import * as service from "@/presentation/services/employmentLlmAdminService";
import * as qualityService from "@/presentation/services/qualityLlmAdminService";
const Page = styled.section`display:flex; flex-direction:column; gap:${p => p.theme.spacing.xl}; max-width:720px;`;
const Card = styled.div`display:flex; flex-direction:column; gap:${p => p.theme.spacing.md}; padding:${p => p.theme.spacing.xl}; border:1px solid ${p => p.theme.colors.border}; border-radius:16px; background:${p => p.theme.colors.surface};`;
export default function EmploymentAiAdminPage() { const [employmentEnabled, setEmploymentEnabled] = useState<boolean | null>(null); const [qualityEnabled, setQualityEnabled] = useState<boolean | null>(null); const [busy, setBusy] = useState<"employment" | "quality" | null>(null); const [error, setError] = useState<string | null>(null); useEffect(() => { Promise.all([service.getEmploymentLlmSettings(), qualityService.getQualityLlmSettings()]).then(([employment, quality]) => { setEmploymentEnabled(employment.minimaxEnabled); setQualityEnabled(quality.minimaxEnabled); }).catch(() => setError("No se pudo cargar la configuración.")); }, []); async function toggle(feature: "employment" | "quality") { const enabled = feature === "employment" ? employmentEnabled : qualityEnabled; if (enabled === null) return; setBusy(feature); setError(null); try { if (feature === "employment") { const next = await service.setMiniMaxEnabled(!enabled); setEmploymentEnabled(next.minimaxEnabled); } else { const next = await qualityService.setQualityMiniMaxEnabled(!enabled); setQualityEnabled(next.minimaxEnabled); } } catch { setError("No se pudo actualizar la configuración."); } finally { setBusy(null); } } const control = (feature: "employment" | "quality", title: string, enabled: boolean | null) => <Card><div><h2>{title}</h2><p>Activa o desactiva las llamadas de IA para esta funcionalidad. Al desactivarla, no se consume capacidad de IA.</p></div><Badge tone={enabled ? "success" : "error"}>{enabled ? "IA activa" : enabled === false ? "IA desactivada" : "Cargando…"}</Badge><Button variant={enabled ? "destructive" : "primary"} onClick={() => toggle(feature)} disabled={busy !== null || enabled === null}>{busy === feature ? "Guardando…" : enabled ? "Desactivar IA" : "Activar IA"}</Button></Card>; return <Page><div><h1>Control de IA</h1><p>Las activaciones se administran de forma independiente por funcionalidad.</p></div>{control("employment", "IA en Empleabilidad", employmentEnabled)}{control("quality", "IA en Calidad", qualityEnabled)}{error && <FormStatusMessage variant="error">{error}</FormStatusMessage>}</Page>; }
